<?php 
/* @var $this Zend\View\PhpRenderer */
?>
<?php echo $this->broker('doctype') ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->broker('headTitle') ?>
    <?php echo $this->broker('headLink') ?>
    <?php echo $this->broker('headStyle') ?>
    <?php //echo $this->jQuery() ?>
    <link rel="stylesheet" type="text/css" href="/styles/styles.css" />
</head>
<body>
<div id="content-page">
    <?php echo $this->render('_header.phtml') ?>

    <div id="content-body">
        <div id="side-content-left">
            <div id="side-menu">
                <?php echo $this->broker('navigation') ?>
            </div>
        </div>
        <?php echo $this->broker('layout')->getlayout()->content ?>
    </div>
    <?php echo $this->render('_footer.phtml') ?>
</div>
</body>
</html>